### ISSUE TITLE
Grue attacks cause server crashes and other unknown server crash

### ISSUE THREAD

**Issue by mevoda** [WTFGeeks/Natural-Magic#93] opened 2014-11-28 05:12 UTC
Whenever a grue spawns on a server it crashes the server. Only way to fix it is to set server to peaceful and have another player go to the area to unload the grue. Also, I was flying around (mark 4 armor) and suddenly server crashed and would continue to crash whenever I would try to relog. We tried the same fix by setting server to peaceful and having another player fly over there but they also crashed the server. So it isnt a hostile mob...in the end we had delete player profiles, respawn in inventory and no one is allowed to go near that area.

crash report: http://pastebin.com/vxwWdZsb

**Comment by dustedone** [comment] 2014-11-28 22:34
In my server I had to go to the config/ lycanitesmobs /shadowmobs-spawning.cfg and turn off spawning for Grue. That was the only fix that worked for me.

**Comment by WTFGeeks** [comment] 2014-11-30 09:30
The Grue issue has been fixed in 0.7.2 as the mob has been disabled, the reason it was crashing is due to it using a enchantment already provided by Artifacts resulting in a crash. The second issue I'm still looking into and is proving a hard one to solve, as the crash only points at world generation and no modded paths giving me no information on what is causing it, I'v never been able to reproduce this so it seems extremely rare, I changed a few things around in 0.7.2 that I think could possibly be the cause of it but I doubt those issues will fx the area affected just stop it happening again. I have a couple of modders looking into it for me. I'll post any information of they come up with anything.

**Closed as completed by WTFGeeks** 2014-11-30 09:30 UTC
