### ISSUE TITLE
Map data being deleted?

### ISSUE THREAD

**Issue by Lexim436** [WTFGeeks/Natural-Magic#14] opened 2014-09-29 13:20 UTC
It seems that every time i logout and login again my map data resets everything from waypoints and places i've explored.

And on a side note the storage crates seem to rearrange the items inside it every time you right click it to open it's inventory

a side side note is maybe the HQM bug where the finished quest aren't being "completed" has something to do with it not being enabled in the server (sometimes it says in my chat that "HQM is not enabled in the server")

**Comment by WTFGeeks** [comment] 2014-09-29 16:12
I'v never had that problem, have you changed any config/added any mods? Storage Crates have always been like that, don't think that'll ever get changed. As far as hqm is not enabled that means it's not forcing you into hardcore mode, that doesn't effect the quests in anyway.

**Comment by Lexim436** [comment] 2014-09-29 22:07
i haven't changed anything since ive downloaded the mod pack it's your original setup or atleast mod setup

**Comment by shadow1moon** [comment] 2014-09-30 12:36
I had the map data not saving where I explore and Waypoints aswell. It just ened up fixing its self after i created a new world.
I would check your map group to see if you have put your waypoints in a different group then you have selected.

**Comment by Lexim436** [comment] 2014-09-30 12:54
^ but that wouldn't explain the map data dissappearing

**Comment by shadow1moon** [comment] 2014-09-30 15:07
Yeah, I haven't been able to reproduce it deleting again. Its only happened once this world. When i bolted through Taint.

Have you tried crafting a regular map to see if that helps it save? I don't know if its the factor, but after i created a map in my first world and then created and started playing in my second world it began working./ Have you tried playing a diffrent world?

**Comment by PurpleHerby** [comment] 2014-10-01 13:12
I have noticed that mapwriter (Opis) can take a long time to complete it's close down process, a few times I have returned to Natural Magic with no map information saved due to my exiting before mapwriter had closed. However, if I watch the console and wait for mapwriter to finish, my map information saves correctly. You can speed the save up by clicking on Singleplayer from the main menu and then cancel (I suspect any option but not tested.).
Either way, mapwriter does appear to have occasional issues when closing a  session.

**Comment by Lexim436** [comment] 2014-10-02 01:08
PurpleHerby but mine happens almost all the time currently all the time

shadow1moon i will try to do multiple test when i finish some stuff irl

**Comment by PurpleHerby** [comment] 2014-10-05 09:34
Lexim, to be honest I'm not convinced that our issues are the same or even related. But, I will say that if I do not click on singleplayer again after exiting my world, mapwriter does not save. 

If your issue IS similar, you can see this happen by watching the console (run minecraft in window dragged to the side with console visible in the background) when you exit your world, it should say that it's unloaded the dimensions and then sit there, if you then click on Singleplayer, you should then see 3 mapwriter entries come up - final one being [mapwriter]: done

If this is not what is happening for you, then our problems aren't related and I'm adding little to nothing in here :)

**Comment by WTFGeeks** [comment] 2014-10-23 12:56
I'v done some testing and checked with other opis users and this seems to be a known issue. In the latest update I added mapwriter as an optional for those that are suffering from the problem. Although if closing the game in the correct procedure seems to allow the mapwriter information to be saved correctly.

**Closed as completed** 2014-11-25 21:59 UTC

**Comment by TeufelPenguin** [comment] 2015-04-02 21:45
I have the same issue, its driving me nuts
