### ISSUE TITLE
Virtual LAN Server-Client delay

### ISSUE THREAD

**Issue by MimsyMan** [WTFGeeks/Natural-Magic#27] opened 2014-10-06 04:34 UTC
So me and a couple buddies wanted to play Natural Magic together, so we got on Evolve (a virtual network client, think Hamachi but less data being eaten up uselessly) and had one of us open a singleplayer world to LAN. Between any of the three of us hosting, the other two have a massive delay between the host and the client. In short, my friend will say "Look at this!" and run over to a hilltop. I'll see him stand around, run in circles around me, and after like 5 minutes, finally go to the hilltop.

**Comment by WTFGeeks** [comment] 2014-10-06 11:33
Duplicate of #7

**Closed as completed by WTFGeeks** 2014-10-06 11:33 UTC
Labels: duplicate
