### ISSUE TITLE
I Feel Great Fire potion will not register

### ISSUE THREAD

**Issue by ghost** [WTFGeeks/Natural-Magic#113] opened 2014-12-10 23:32 UTC
I have 2 in my inventory, and I made them in the brewing stand, but the quest will not recognize them.  It recognizes the Regen and the Instant health, but not the Fire Resistance potion.

**Comment by WTFGeeks** [comment] 2014-12-11 10:36
duplicate of #101

**Closed as completed by WTFGeeks** 2014-12-11 10:36 UTC

**Comment by ghost** [comment] 2014-12-11 15:21
Sorry, I tried a search and didn't find it.
