### ISSUE TITLE
Lorepages

### ISSUE THREAD

**Issue by Trastos** [WTFGeeks/Natural-Magic#38] opened 2014-10-16 07:49 UTC

**Comment by DucktorShvat** [comment] 2014-10-16 21:03
Me and my mates have an issue with lore pages. Specifically, on the first quest from the hardcore questing mod, when we claim the reward and get the lore page, we get kicked from server and can't reconnect. Upon deleting the player's data and clearing their inventory they are allowed to connect again. Have not tested if lore pages work in single player.

**Comment by WTFGeeks** [comment] 2014-10-16 22:06
I'm unable to reproduce this issue server side, please post player/server crash logs sp I can see the problem you're having your end.

**Comment by DucktorShvat** [comment] 2014-10-17 06:27
Here is a copy of the logs:

https://dl.dropboxusercontent.com/u/65439948/Lorepage%20crash%20logs.txt

**Comment by Kuroimitsukai** [comment] 2014-10-30 03:53
I'm also getting the same crash with the same log reports when the person joins. i was able to get back on but only after deleting the item from my inventory with NBTExplorer

**Comment by WTFGeeks** [comment] 2014-11-09 20:03
This is resolved in v0.7 please make sue to check the changelog as it's a rather large update.

**Closed as completed by WTFGeeks** 2014-11-09 20:03 UTC
